# @todo build on CI server first, then copy files to avoid downtime

name: Deploy FV UAT

on:
  push:
    branches:
      - fv-uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build containers
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/game
            git reset --hard
            git checkout prod
            git pull
            npm install
            npm run build
            pm2 reload game
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
